### ISSUE TITLE
question about vac

### ISSUE THREAD

**Issue by MaTachi20** [robbyz512/dota2-minify#6]
is this mod gonna be detected as a cheat by vac because i saw ur dota2patcher that allowing dotaplus for free and i think its illegal no?

**Comment by robbyz512** [comment]
loading mods into dota will never get you banned because thousands of people do this to create custom arcade maps and skins, and valve teaches everyone how to mod on their wiki. 

Also dota2patcher isn't my program, it's just a way to enable mods for online matchmaking or else you get a warning saying mods are disabled in online play.
